import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
//components
import SidebarMenu from '@/components/menus/SidebarMenu'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class='flex'>
        
        <SidebarMenu />

        <div class={styles.container}>
          <div class={styles.containerInner}>

              <div class={styles.header}>
              <h1 class="text-[2.2rem] font-semibold">Welcome to Podium!</h1>
              <p class='text-[1.2rem]'>Sign in below or Sign Up</p>
              </div>

                <div class=''>
                  <p class='py-3 text-[1.5rem] font-medium'>Sign In</p>
                  <input class='w-full mb-3' type='text' placeholder='Email'/>
                  <input class='w-full' type='text' placeholder='Password'/>
                    <div class='flex items-center p-2 gap-1'>
                      <input class='my-2' id='remember' type='checkbox' /><br/>
                      <label for='remember'>Remember me</label>
                    </div>
                  <button class='p-[10px] w-full bg-black text-white'>Sign In</button>
                    <p class='py-3 text-right'>Forgot your password?</p>
                </div>

                <div class='flex flex-col gap-[13px] text-center'>
                  <p>Or</p>
                  <button class='p-[10px] w-full bg-black text-white'>Sign In with Google</button>
                  <button class='p-[10px] w-full bg-black text-white'>Sign In with Facebook</button>
                </div>
          </div>
        </div>
      
      
      </main>
    </>
  )
}
