import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
//components
import SidePicture from '@/components/menus/SidePicture'

export default function Login() {
  return (
    <>
      <Head>
        <title>Podium | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class='flex'>

        <div class={styles.container}>
          <div class={styles.containerInner}>

              <div class={styles.header}>
              <h1 class="text-[2.2rem] font-semibold">Welcome to Podium!</h1>
              <p class='text-[1.2rem]'>Sign in below or <a href='/signup' class='cursor-pointer font-bold underline'>Sign Up</a></p>
              </div>

                <div class=''>
                  <p class='py-3 text-[1.36rem] font-medium'>Sign In</p>
                  <input class='w-full mb-3' type='text' placeholder='Email'/>
                  <input class='w-full' type='text' placeholder='Password'/>
                    <div class='flex items-center p-2 gap-1'>
                      <input class='my-2' id='remember' type='checkbox' /><br/>
                      <label for='remember'>Remember me</label>
                    </div>
                  <button class='p-[10px] w-full bg-black text-white rounded-sm'>Sign In</button>
                    <p class='py-3 text-right'>Forgot your password?</p>
                </div>

                <div class='flex flex-col gap-[13px] text-center'>
                  <p>Or</p>
                  <button class='p-[10px] w-full bg-black text-white rounded-sm'>Sign In with Google</button>
                  <button class='p-[10px] w-full bg-black text-white rounded-sm'>Sign In with Facebook</button>
                </div>
          </div>
        </div>
      
        <SidePicture image='https://img.freepik.com/free-photo/soccer-players-action-professional-stadium_654080-1194.jpg?w=1380&t=st=1675121820~exp=1675122420~hmac=45c9eb84452caed580344f5536705dcdabc9848e820707a5bf1385d8cc5e5b99' />
      
      </main>
    </>
  )
}
