import React, {useState} from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
//components
import SidePicture from '@/components/menus/SidePicture'

export default function Signup() {

    const [firstName, setFirstName] = useState('');
    const [lastName, setLastName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [authority, setAuthority] = useState('');

  return (
    <>
      <Head>
        <title>Podium | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class='flex'>

        <div class={styles.container}>
          <div class={styles.containerInner}>

              <div class={styles.header}>
              <h1 class="text-[2.2rem] font-semibold">Welcome to Podium!</h1>
              <p class='text-[1.2rem]'>Create an account or <a href='/login' class='cursor-pointer font-bold underline'>Sign In</a></p>
              </div>

                <div class=''>
                  <p class='py-3 text-[1.36rem] font-medium'>Sign Up</p>
                  <div class='flex gap-2'>
                    <input class='' type='text' value={firstName} onChange={(e) => setFirstName(e.target.value)} placeholder='First Name'/>
                    <input class='' type='text' value={lastName} onChange={(e) => setLastName(e.target.value)} placeholder='Last Name'/>
                  </div>
                  <div class='my-3'>
                    <input class='w-full mb-3' type='text' value={email} onChange={(e) => setEmail(e.target.value)} placeholder='Email'/>
                    <input class='w-full' type='password' maxlength="8" value={password} onChange={(e) => setPassword(e.target.value)} placeholder='Password (Max 8 characters)'/>
                    </div>

                    <select class="w-full" value={authority} onChange={(e) => setAuthority(e.target.value)} id="">
                    <option hidden>Choose Authority</option>  
                    <option value="player">Player</option>
                    <option value="captain">Team Captain</option>
                    <option value="admin">Admin</option>
                    </select>

                  <button class='mt-5 p-[10px] w-full bg-black text-white rounded-sm'>Sign Up</button>
                    <p class='py-3 text-right'></p>
                </div>

                <div class='flex flex-col gap-[13px] text-center'>
                  <p>Or</p>
                  <button type="button" class="text-white bg-[#4285F4] hover:bg-[#4285F4]/90 focus:ring-4 focus:outline-none focus:ring-[#4285F4]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#4285F4]/55 mr-2 mb-2 justify-center">
                  <svg class="w-4 h-4 mr-2 -ml-1" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="google" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512"><path fill="currentColor" d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"></path></svg>
                  Sign in with Google
                </button>
                
                <button type="button" class="text-white bg-[#3b5998] hover:bg-[#3b5998]/90 focus:ring-4 focus:outline-none focus:ring-[#3b5998]/50 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:focus:ring-[#3b5998]/55 mr-2 mb-2 justify-center">
                <svg class="w-4 h-4 mr-2 -ml-1" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-f" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M279.1 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.4 0 225.4 0c-73.22 0-121.1 44.38-121.1 124.7v70.62H22.89V288h81.39v224h100.2V288z"></path></svg>
                Sign in with Facebook
              </button>
                </div>
          </div>
        </div>
      
        <SidePicture image='https://img.freepik.com/free-photo/soccer-player-action-stadium_1150-14607.jpg?w=1060&t=st=1675122690~exp=1675123290~hmac=851a091275701f2eed1ad6a5eb968ce238c0f1585762808af36e2767eef179aa' />
      
      </main>
    </>
  )
}
