import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
//components
import SidePicture from '@/components/menus/SidePicture'

export default function Signup() {
  return (
    <>
      <Head>
        <title>Podium | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class='flex'>

        <div class={styles.container}>
          <div class={styles.containerInner}>

              <div class={styles.header}>
              <h1 class="text-[2.2rem] font-semibold">Welcome to Podium!</h1>
              <p class='text-[1.2rem]'>Create an account or <a href='/login' class='cursor-pointer font-bold underline'>Sign In</a></p>
              </div>

                <div class=''>
                  <p class='py-3 text-[1.36rem] font-medium'>Sign Up</p>
                  <div class='flex gap-2'>
                    <input class='' type='text' placeholder='First Name'/>
                    <input class='' type='text' placeholder='Last Name'/>
                  </div>
                  <div class='my-3'>
                    <input class='w-full mb-3' type='text' placeholder='Email'/>
                    <input class='w-full' type='text' placeholder='Password'/>
                    </div>

                    <select class="" id="">
                    <option hidden>Choose Authority</option>  
                    <option value="player">Player</option>
                    <option value="captain">Team Captain</option>
                    <option value="admin">Admin</option>
                    </select>

                  <button class='mt-5 p-[10px] w-full bg-black text-white rounded-sm'>Sign Up</button>
                    <p class='py-3 text-right'></p>
                </div>

                <div class='flex flex-col gap-[13px] text-center'>
                  <p>Or</p>
                  <button class='p-[10px] w-full bg-black text-white rounded-sm'>Sign Up with Google</button>
                  <button class='p-[10px] w-full bg-black text-white rounded-sm'>Sign Up with Facebook</button>
                </div>
          </div>
        </div>
      
        <SidePicture image='https://img.freepik.com/free-photo/soccer-player-action-stadium_1150-14607.jpg?w=1060&t=st=1675122690~exp=1675123290~hmac=851a091275701f2eed1ad6a5eb968ce238c0f1585762808af36e2767eef179aa' />
      
      </main>
    </>
  )
}
